### ISSUE TITLE
Breite des Widgets für "Tabellen" bei weniger als 480px abgeschnitten

### ISSUE THREAD

**Issue by kekkeller** [mheob/include-fussball-de-widgets#720]
Hallo Alex,
ich habe festgestellt, dass das Widget beim Anzeigen für Tabellen bei weniger als 480px abgeschnitten ist:
![image](https://github.com/mheob/include-fussball-de-widgets/assets/55140082/a49af7c8-9fe5-43df-b0dc-7eedb66dc95a)

Ich habe es mit verschiedenen Einstellungen für iFrame width probiert, habe auch alle Möglichkeiten zum einbinden Versucht.

Gibt es deinerseits eine Idee den Fehler zu beheben ?
Liebe Grüße

**Comment by mheob** [comment]
Hallo @kekkeller,

vielleicht schaust du dir bspw. die Einbindung auf https://www.hsv-neuwied.de/senioren/erste/tabelle/ an. Dort funktioniert es relativ gut. Wenn es zu klein wird, muss halt horizontal gescrollt werden.

Das Thema mit den Breiten ist leider ein großes Problem, dass fussball.de auch schon ewig bekannt ist.

Die einzige Stelle, wo du die Widget-Breite einstellen kannst, ist unter:

https://www.fussball.de/my.account.admin.widgets#!/ —> Vorschau —> Breite in Pixeln

Da geht dann der Bereich von 400px bis 900px.
Da es sich um feste Werte handelt, sieht das eine auf Mobile besser aus, das andere auf dem Desktop. Beides uncool. Aber evtl. kann man mit den Werten ein wenig herumspielen.

Grüße
Alex

**Comment by mheob** [comment]
Eine andere Idee wäre noch:

Versuch mal das Widget außerhalb der Tabs zu machen. Diese Tabs machen leider regelmäßig Probleme mit der Kommunikation zwischen deiner Seite und mit fussball.de.

Evtl. kann fussball.de die korrekte, aktuelle Breite nicht ermitteln.

**Comment by kekkeller** [comment]
Danke dir für die super Schnelle Antwort!

Es gibt scheinbar ein Problem bei Fußball.de 
![image](https://github.com/mheob/include-fussball-de-widgets/assets/55140082/0a6f0352-b777-4e15-ad95-e849d54d718a)
Die Tabellen der "Ligen" scheinen wohl sehr schlecht zu funktionieren.

https://scv-griesheim.de/1-mannschaft/
Auf dieser Seite hatte ich die Einbindung Versucht, der Screenshot war von deiner Testseite die mal verlinkt wurde.

Wenn das Widget ja auch auf Füssball.de nicht funktioniert, wird das Widget das leider nicht Fixen können.
Ich trete ggf. mal mit Fussball.de in Kontakt aber wie ich durch die Zeilen lesen konnte, möchte dort keiner Fehler beheben.

Danke dir für die Hilfe.

**Comment by mheob** [comment]
Dein Screenshot sagt schon alles. Und ja, du hast recht. Unter der Haube wird durch mein Plugin bloß die Einbindung des iFrames erleichtert und ein paar Kleinigkeiten optimiert, soweit ich konnte. Der Inhalt an sich kommt direkt von fussball.de. Funktioniert er dort schon nicht, wird er auch durch mich nicht gehen.

Und, ja gerne fussball.de nerven. Gefühlt hat fussball.de trotz diverser Wünsche seit Release der Widgets so gut wie nichts mehr daran gemacht.

Ich träume auch immer noch davon, dass sie eine API statt den iFrames zur Verfügung stellen. Dann könnte jeder Nutzer viel mehr selbst entscheiden und machen. Aber in einer API kann keine Werbung ausgeliefert werden 😁

**Comment by kekkeller** [comment]
Hattest du mal versucht per CSS Klassen auf das iFrame zuzugreifen um ggf. die Spalte der Mannschaften schmaler zu machen ?
So tief bin ich dann leider doch nicht in der Thematik.

**Comment by mheob** [comment]
Sorry, iFrames sind uncool. Und in diesem speziellen Fall arbeitet fussball.de stark mit JavaScript, was die Darstellung angeht.

**Comment by kekkeller** [comment]
Danke dir! ich mach das Ticket mal zu.

**Comment by kekkeller** [comment]
@mheob als Info für dich, falls noch einmal Jemand danach Fragt. Es gibt bei einem Mannschaftsspielplan die Möglichkeit einen Harken in den Einstellungen zu setzen für "mit Tabelle" diese Tabelle ist dann Responsive auch in kleinen Pixel Bereichen. 

Somit habe ich das Problem Final lösen können.

**Comment by mheob** [comment]
Danke!
